// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parorendeportalen.Api.Data;

#nullable disable

namespace Parorendeportalen.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914110804_AddVisitWritePath")]
    partial class AddVisitWritePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parorendeportalen.Api.Integrations.Sync.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Truncated")
                        .HasColumnType("boolean");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer");

                    b.Property<int>("Unresolved")
                        .HasColumnType("integer");

                    b.Property<int>("Updated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "ResourceType", "StartedAt");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Integrations.Sync.SyncWatermark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContinuationToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("SourceUpdatedThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UnresolvedFrom")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "ResourceType")
                        .IsUnique();

                    b.ToTable("SyncWatermarks");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.AccessLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NextOfKinId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId", "OccurredAt");

                    b.HasIndex("NextOfKinId", "OccurredAt");

                    b.ToTable("AccessLogEntries");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.CareRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalIdHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("NationalIdHash")
                        .IsUnique()
                        .HasFilter("\"NationalIdHash\" IS NOT NULL");

                    b.ToTable("CareRecipients");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.ChangeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("VisitId");

                    b.ToTable("ChangeEvents");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Consent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NextOfKinId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NextOfKinId");

                    b.HasIndex("CareRecipientId", "NextOfKinId", "Category")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.KinshipGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<int>("NextOfKinId")
                        .HasColumnType("integer");

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId");

                    b.HasIndex("NextOfKinId", "CareRecipientId")
                        .IsUnique();

                    b.ToTable("KinshipGrants");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.NextOfKin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NationalIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("NationalIdHash")
                        .IsUnique();

                    b.ToTable("NextOfKin");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ChangeEventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NextOfKinId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId");

                    b.HasIndex("ChangeEventId", "NextOfKinId")
                        .IsUnique();

                    b.HasIndex("NextOfKinId", "OccurredAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NextOfKinId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NextOfKinId", "Kind")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Vedtak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId", "ValidFrom");

                    b.ToTable("Vedtak");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.VedtakTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("VedtakId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VedtakId", "Sequence");

                    b.ToTable("VedtakTasks");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("CaregiverName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByNextOfKinId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Visibility")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId");

                    b.HasIndex("CreatedByNextOfKinId");

                    b.HasIndex("ExternalId", "Origin")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Visits", t =>
                        {
                            t.HasCheckConstraint("CK_Visits_AuthoredEntryHasVisibility", "(\"CreatedByNextOfKinId\" IS NULL) = (\"Visibility\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.VisitComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorNextOfKinId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorNextOfKinId");

                    b.HasIndex("VisitId", "CreatedAt");

                    b.ToTable("VisitComments");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.ChangeEvent", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany()
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parorendeportalen.Api.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CareRecipient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Consent", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany("Consents")
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parorendeportalen.Api.Models.NextOfKin", "NextOfKin")
                        .WithMany("Consents")
                        .HasForeignKey("NextOfKinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareRecipient");

                    b.Navigation("NextOfKin");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.KinshipGrant", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany("Grants")
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parorendeportalen.Api.Models.NextOfKin", "NextOfKin")
                        .WithMany("Grants")
                        .HasForeignKey("NextOfKinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareRecipient");

                    b.Navigation("NextOfKin");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Notification", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany()
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parorendeportalen.Api.Models.NextOfKin", "NextOfKin")
                        .WithMany()
                        .HasForeignKey("NextOfKinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareRecipient");

                    b.Navigation("NextOfKin");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.NotificationPreference", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.NextOfKin", "NextOfKin")
                        .WithMany()
                        .HasForeignKey("NextOfKinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextOfKin");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Vedtak", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany()
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Parorendeportalen.Api.Models.RecurrenceRule", "Recurrence", b1 =>
                        {
                            b1.Property<int>("VedtakId")
                                .HasColumnType("integer");

                            b1.Property<int>("Days")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceDays");

                            b1.Property<int>("TimesPerDay")
                                .HasColumnType("integer")
                                .HasColumnName("RecurrenceTimesPerDay");

                            b1.HasKey("VedtakId");

                            b1.ToTable("Vedtak");

                            b1.WithOwner()
                                .HasForeignKey("VedtakId");
                        });

                    b.Navigation("CareRecipient");

                    b.Navigation("Recurrence")
                        .IsRequired();
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.VedtakTask", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.Vedtak", "Vedtak")
                        .WithMany("Tasks")
                        .HasForeignKey("VedtakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vedtak");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Visit", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany("Visits")
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parorendeportalen.Api.Models.NextOfKin", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByNextOfKinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CareRecipient");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.VisitComment", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.NextOfKin", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorNextOfKinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parorendeportalen.Api.Models.Visit", "Visit")
                        .WithMany("Comments")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.CareRecipient", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Grants");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.NextOfKin", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Grants");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Vedtak", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Visit", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
