// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parorendeportalen.Api.Data;

#nullable disable

namespace Parorendeportalen.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parorendeportalen.Api.Models.CareRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CareRecipients");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.NextOfKin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NationalIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Relationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("NationalIdHash")
                        .IsUnique();

                    b.ToTable("NextOfKin");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CareRecipientId")
                        .HasColumnType("integer");

                    b.Property<string>("CaregiverName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.NextOfKin", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany("NextOfKin")
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareRecipient");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.Visit", b =>
                {
                    b.HasOne("Parorendeportalen.Api.Models.CareRecipient", "CareRecipient")
                        .WithMany("Visits")
                        .HasForeignKey("CareRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareRecipient");
                });

            modelBuilder.Entity("Parorendeportalen.Api.Models.CareRecipient", b =>
                {
                    b.Navigation("NextOfKin");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
