@Parorendeportalen.Api_HostAddress = http://localhost:5109

GET {{Parorendeportalen.Api_HostAddress}}/api/auth/login?returnUrl=/api/auth/me

###

GET {{Parorendeportalen.Api_HostAddress}}/api/auth/me
Accept: application/json

###

POST {{Parorendeportalen.Api_HostAddress}}/api/auth/logout

###

GET {{Parorendeportalen.Api_HostAddress}}/api/visits
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/api/visits?pageNumber=1&pageSize=5&from=2026-08-01T00:00:00%2B02:00&to=2026-08-31T23:59:59%2B02:00
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/api/visits/1
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/api/visits/999
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/health
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/api/carerecipients
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/api/carerecipients/1
Accept: application/json

###

GET {{Parorendeportalen.Api_HostAddress}}/api/carerecipients/999
Accept: application/json

###
